### ISSUE TITLE
Attendees: set icon for those that have no gravatar

### ISSUE THREAD

**Issue by ePascalC** [wceu/wceu2024#3]
Request to Design: https://wceu.slack.com/archives/C030KB1QM/p1714982718328909

CSS needed to add a background image on #tix-attendees li::before , and in Settings > Discussions set the “Default avatar” to blank. So technically the background image is there for everyone, but if they have avatars it’s hidden.

**Comment by ePascalC** [comment]
Something like:
`{
	content: "";
	display: inline-block;
	position: absolute;
	inset: 0;
	margin: 0 auto;
	height: 96px;
	width: 96px;
	z-index: -1;
	background-image: url(https://europe.wordcamp.org/2024/files/2024/05/noavatar.png);
	background-size: contain;
}`

**Comment by CarlosLongarela** [comment]
Fixed https://github.com/wceu/wceu2024/blob/32c39b5143adf11392b6599d8c6778fe263dce81/live-css/live-css-wceu-2024.css#L391
